// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteCamp.Portal.Core.Database;

namespace RemoteCamp.Portal.Core.Database.Migrations
{
    [DbContext(typeof(RemoteCampContext))]
    [Migration("20190716155639_UserCalendarItem.Header")]
    partial class UserCalendarItemHeader
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RemoteCamp.Portal.Core.Database.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(320);

                    b.Property<int>("RcXoId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RemoteCamp.Portal.Core.Database.Model.UserCalendarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Day")
                        .HasMaxLength(10);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Header")
                        .HasMaxLength(100);

                    b.Property<int>("WeekNumber");

                    b.HasKey("Id");

                    b.ToTable("UserCalendarItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Friday",
                            Description = "You are technically and mentally prepared to the adventure. All is set up. Your assignments will be available on Monday.",
                            WeekNumber = 0
                        },
                        new
                        {
                            Id = 2,
                            Day = "Monday",
                            Description = @"You know your plan for this week.
                                You know how the tracker works.
                                You started your alignment with the Manager.
                                You started to work on your assignments and completed 10% of the weekly target",
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 3,
                            Day = "Tuesday",
                            Description = @"You know your failures.
                                You are identified your hardest problem and started to think how to resolve it,
                                and discussed it with your manager.
                                You completed 40% of your weekly target.",
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            Day = "Wednesday",
                            Description = @"You planned your improvements.
                                You completed 70% of your weekly target.
                                Your WSPro deck has TMS and improvement plan linked.",
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            Day = "Thursday",
                            Description = @"You started to fill WSPro deck with your insights.
                                You completed 90% of your weekly target.",
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 6,
                            Day = "Friday",
                            Description = @"You have 2 WSPro insights in your deck.
                                You completed 100% of your weekly target.
                                You provided the NPS to the RC management.",
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 7,
                            Day = "Monday",
                            Description = @"You know your plan for this week.
                                You started to work on your assignments and completed 25% of the weekly target.
                                You planned your improvements(by 25%) and documented it.
                                You found the tools to improve your productivity.
                                You have 3 WSPro insights in your deck",
                            Header = "Productivity vs.week1 increased + 25%",
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 8,
                            Day = "Tuesday",
                            Description = @"You discussed your hardest problem with your manager.
                                You completed 50% of your weekly target.
                                You compared your results with the previous week and documented the changes.
                                You have 4 WSPro insights,
                                1 negative feedback and 2 TMSs in your deck",
                            Header = "Productivity vs.week1 increased + 25%",
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            Day = "Wednesday",
                            Description = @"You completed 75% of your weekly target.
                                You completed the WSPro section in your deck
                                You completed Negative feedback section of your deck",
                            Header = "Productivity vs.week1 increased + 25%",
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 10,
                            Day = "Thursday",
                            Description = @"You completed 100% of your weekly target.
                                You reviewed WSPro section with your manager and addressed his feedback",
                            Header = "Productivity vs.week1 increased + 25%",
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 11,
                            Day = "Friday",
                            Description = @"You checked all failures and caught up with all the tasks undone for this week.
                                You created the draft of your idea to double the productivity.
                                You provided the NPS to the RC management.",
                            Header = "Productivity vs.week1 increased + 25%",
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 12,
                            Day = "Monday",
                            Description = @"You know your plan for this week.
                                You started to work on your assignments and completed 25% of the weekly target.
                                You planned your improvements(by 25%) and documented it.
                                You refined your idea to double the productivity.
                                You added 1 feedback about the RC to your deck",
                            Header = "Productivity vs.week2 increased + 25%",
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 13,
                            Day = "Tuesday",
                            Description = @"You discussed your hardest problem with your manager.
                                You completed 50% of your weekly target.
                                You compared your results with the previous week and documented the changes.
                                You have 2 feedbacks to RC in your deck",
                            Header = "Productivity vs.week2 increased + 25%",
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 14,
                            Day = "Wednesday",
                            Description = @"You completed 75% of your weekly target.
                                You completed the ""Provide feedback"" section in your deck",
                            Header = "Productivity vs.week2 increased + 25%",
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 15,
                            Day = "Thursday",
                            Description = @"You completed 100% of your weekly target.
                                You reviewed WSPro section,
                                Provide feedback,
                                Negative feedback sections with your manager and addressed his feedback",
                            Header = "Productivity vs.week2 increased + 25%",
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 16,
                            Day = "Friday",
                            Description = @"You checked all failures and caught up with all the tasks undone for this week.
                                You refined your idea to double the productivity based on the results of the previous week.
                                Your WSPro deck is ready except the final results page.
                                You provided the NPS to the RC management.",
                            Header = "Productivity vs.week2 increased + 25%",
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 17,
                            Day = "Monday",
                            Description = @"You know your plan for this week.
                                You started to work on your assignments and completed 25% of the weekly target.
                                You planned your improvements(by 25%) and documented it.
                                You refined your idea to double the productivity.",
                            Header = "Productivity vs.week3 increased + 25%",
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 18,
                            Day = "Tuesday",
                            Description = @"You discussed your hardest problem with your manager.
                                You completed 50% of your weekly target.
                                You compared your results with the previous week and documented the changes.",
                            Header = "Productivity vs.week3 increased + 25%",
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 19,
                            Day = "Wednesday",
                            Description = @"You completed 75% of your weekly target.
                                 You filled the ""Results"" section of your deck(prev.3 weeks)",
                            Header = "Productivity vs.week3 increased + 25%",
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 20,
                            Day = "Thursday",
                            Description = @"You completed 100% of your weekly target.
                                You addressed all the feedbacks and your WSPro deck is ready",
                            Header = "Productivity vs.week3 increased + 25%",
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 21,
                            Day = "Friday",
                            Description = @"You checked all failures and caught up with all the tasks undone for this week.
                                You have graduated from the RemoteCamp.
                                You enjoy your party on this occasion.",
                            Header = "Productivity vs.week3 increased + 25%",
                            WeekNumber = 4
                        });
                });

            modelBuilder.Entity("RemoteCamp.Portal.Core.Database.Model.UserCalendarItemAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int>("Duration");

                    b.Property<string>("Url")
                        .HasMaxLength(2083);

                    b.Property<int>("UserCalendarItemId");

                    b.HasKey("Id");

                    b.HasIndex("UserCalendarItemId");

                    b.ToTable("UserCalendarItemActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Get and read the welcome email from RemoteCamp management",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Check all the accesses (todo: add which exactly)",
                            Duration = 60,
                            Url = "",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Report non-working accesses to the RemoteCamp SEM",
                            Duration = 20,
                            Url = "",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kick-off call",
                            Duration = 60,
                            Url = "",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Read \"Quality and common terms we use\"",
                            Duration = 7,
                            Url = "https://drive.google.com/open?id=13x4k7OlM-qoZIfwnr3FqeQKpMBmOJ5VD0IEsGiSMOvM",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Read \"How will you pass the RemoteCamp\"",
                            Duration = 6,
                            Url = "https://drive.google.com/open?id=1TE952cAjQo_MTVxBNKB4F4GsrwmFNMEI3JXXilS_M0Y",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Watch \"Quality-30/01/2019.mp4\"",
                            Duration = 27,
                            Url = "https://drive.google.com/drive/u/0/folders/1eiGuCV72FUWezStfqNq_KCXXgIuratjm",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Read \"Worksmart tool certified\"",
                            Duration = 5,
                            Url = "https://drive.google.com/open?id=1yjIVcSKnAtgIgZ52W2jPDb9OC8K6RvOb5V2n1KOmCBs",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Read \"Intensity and focus blocks\"",
                            Duration = 8,
                            Url = "https://drive.google.com/open?id=1dJPwpR5BREoMZa8CV2sVkwUYuaAZDg0AokvkvHhIH-Q",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Read \"CiC Framework\"",
                            Duration = 15,
                            Url = "https://docs.google.com/document/d/1IDD5TN33cQI65p2lSwnu285fJXSOVSe2ebNu1gIF5ak/edit",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Watch \"Anti-cheating policy\"",
                            Duration = 28,
                            Url = "https://drive.google.com/open?id=1ToaleLywRtkhudjxBH9nCZAvdY1G27SH",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Watch \"Tackling the Hardest Problem\"",
                            Duration = 24,
                            Url = "https://drive.google.com/open?id=1WbcAloWNZjJrWsYrFItyFUAmehm64ZFd",
                            UserCalendarItemId = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Get the list of assignments (jira) and go through it",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Make a weekly plan of deliveries. Recommended distribution of load is: 10/30/30/20/10+fix+catchup.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "CiC with Manager",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Ask technical questions, setup projects, understand the requirements to the job done (IQBs), watch and read technical documentation applicable to your track",
                            Duration = 240,
                            Url = "",
                            UserCalendarItemId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Development work",
                            Duration = 160,
                            Url = "",
                            UserCalendarItemId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Read \"Welcome Negative feedback\"",
                            Duration = 5,
                            Url = "https://drive.google.com/open?id=1QNGyddEVA6mO8sbi4CZ8M-XxaybskglUP38gSqEgtmo",
                            UserCalendarItemId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Read \"Seek Continuous Improvement / Experiment\"",
                            Duration = 10,
                            Url = "https://drive.google.com/open?id=1-4Zoh9MeXadFMxmF9sgsaP-4jK0VWCFBrr7urCaenDA",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 21,
                            Description = "CiC with Manager",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Development work",
                            Duration = 350,
                            Url = "",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 23,
                            Description = "Make TMS video of 1 unit produced",
                            Duration = 0,
                            Url = "https://drive.google.com/file/d/0BzSXGty9sV6KRGp1aHNPa2dkWTQ/view",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "\"Be an expert / Tackle the hardest problem\"",
                            Duration = 6,
                            Url = "https://drive.google.com/open?id=1IN3V4uEnjL2J5AnwdDmIABwCr3d6fzEJE_tDG7qXdqM",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 25,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Create your copy of WSPro deck, add your TMS.",
                            Duration = 39,
                            Url = "https://docs.google.com/document/u/1/d/1oc5kgAfOZgvOhvwHjLjyZJmPKkxMmwtg7vt-rncW1ss/edit",
                            UserCalendarItemId = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Read \"Find Tools That Improve Your Own Productivity\"",
                            Duration = 5,
                            Url = "https://drive.google.com/open?id=1wKKuzWFiL6nDIrq9aNSss6EqKugZNgJku57gfdolcCM",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 28,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 29,
                            Description = "CiC with Manager",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 30,
                            Description = "Development work",
                            Duration = 350,
                            Url = "",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 31,
                            Description = "Read \"Improving quality and productivity\"",
                            Duration = 6,
                            Url = "https://drive.google.com/open?id=12M7I2E4T47bk0jKprtdlsd8gt9iN4NVP7P4KLq-uv38",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 32,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 33,
                            Description = "Identify possible improvements, create plan how do you want to achieve your target",
                            Duration = 44,
                            Url = "",
                            UserCalendarItemId = 4
                        },
                        new
                        {
                            Id = 34,
                            Description = "Read \"Follow your calendar\"",
                            Duration = 5,
                            Url = "https://drive.google.com/open?id=1u90OxXmLrfSsphaTJ81Gu-o5JU4aj5tqw36K_K6YoV4",
                            UserCalendarItemId = 5
                        },
                        new
                        {
                            Id = 35,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 5
                        },
                        new
                        {
                            Id = 36,
                            Description = "CiC with Manager",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 5
                        },
                        new
                        {
                            Id = 37,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 5
                        },
                        new
                        {
                            Id = 38,
                            Description = "Read \"Put yourself in Customer\"''\"s shoes\"",
                            Duration = 6,
                            Url = "https://drive.google.com/open?id=1J9kRxC_8dW2--6Jn_FxaQ1pa8KgSE-eYHj4CkwIfoe4",
                            UserCalendarItemId = 5
                        },
                        new
                        {
                            Id = 39,
                            Description = "Check your WSPro statistics. Check your results. Find 1 insight and put it to WSPro deck",
                            Duration = 44,
                            Url = "",
                            UserCalendarItemId = 5
                        },
                        new
                        {
                            Id = 40,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 6
                        },
                        new
                        {
                            Id = 41,
                            Description = "CiC with Manager",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 6
                        },
                        new
                        {
                            Id = 42,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 6
                        },
                        new
                        {
                            Id = 43,
                            Description = "Read \"Give Improvement Feedback\"",
                            Duration = 6,
                            Url = "https://drive.google.com/open?id=1Mt1HyCnSsU69yBmndtY0pYxtN787OD-gkjJpA3XLjeE",
                            UserCalendarItemId = 6
                        },
                        new
                        {
                            Id = 44,
                            Description = "Check your WSPro statistics. Check your results. Find 1 insight and put it to WSPro deck",
                            Duration = 44,
                            Url = "",
                            UserCalendarItemId = 6
                        },
                        new
                        {
                            Id = 45,
                            Description = "Fill the NPS RemoteCamp form to summarize your experience of the week",
                            Duration = 7,
                            Url = "",
                            UserCalendarItemId = 6
                        },
                        new
                        {
                            Id = 46,
                            Description = "Make a weekly plan of deliveries. Recommended distribution of load is: 25/25/25/25/fix+catchup",
                            Duration = 30,
                            Url = "https://drive.google.com/open?id=1YMslqRjd3tedFUXgUjHKZqjegXpF9Swn",
                            UserCalendarItemId = 7
                        },
                        new
                        {
                            Id = 47,
                            Description = "Read \"Make Automations Suggestions to Team Lead\"",
                            Duration = 5,
                            Url = "https://drive.google.com/open?id=1WKGk2q2dfhP5_nB-HuQxzp04SIN4VL3gf2WlK7c5B9Q",
                            UserCalendarItemId = 7
                        },
                        new
                        {
                            Id = 48,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 7
                        },
                        new
                        {
                            Id = 49,
                            Description = "Analyse your last week performance. Plan this week improvements, document this plan. Search the tools to improve your productivity.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 7
                        },
                        new
                        {
                            Id = 50,
                            Description = "Development work",
                            Duration = 360,
                            Url = "",
                            UserCalendarItemId = 7
                        },
                        new
                        {
                            Id = 51,
                            Description = "Add 1 WSPro insight to WSPro deck",
                            Duration = 25,
                            Url = "",
                            UserCalendarItemId = 7
                        },
                        new
                        {
                            Id = 52,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 53,
                            Description = "CiC with Manager, ask for the negative feedback",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 54,
                            Description = "Development work",
                            Duration = 350,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 55,
                            Description = "Make TMS video of 1 unit produced",
                            Duration = 0,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 56,
                            Description = "Compare TMS for this week and the previous, document the changes",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 57,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 58,
                            Description = "Add 1 WSPro insight to WSPro deck",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 59,
                            Description = "Add 1 Negative feedback to WSPro deck",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 8
                        },
                        new
                        {
                            Id = 60,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 9
                        },
                        new
                        {
                            Id = 61,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 9
                        },
                        new
                        {
                            Id = 62,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 9
                        },
                        new
                        {
                            Id = 63,
                            Description = "Finish WSPro page in deck",
                            Duration = 40,
                            Url = "",
                            UserCalendarItemId = 9
                        },
                        new
                        {
                            Id = 64,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 10
                        },
                        new
                        {
                            Id = 65,
                            Description = "CiC with Manager, ask for negative feedback",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 10
                        },
                        new
                        {
                            Id = 66,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 10
                        },
                        new
                        {
                            Id = 67,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 10
                        },
                        new
                        {
                            Id = 68,
                            Description = "Add 1 negative feedback to your deck",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 10
                        },
                        new
                        {
                            Id = 69,
                            Description = "Address manager\"''\"s feedback in your deck",
                            Duration = 15,
                            Url = "",
                            UserCalendarItemId = 10
                        },
                        new
                        {
                            Id = 70,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 11
                        },
                        new
                        {
                            Id = 71,
                            Description = "Development work",
                            Duration = 350,
                            Url = "",
                            UserCalendarItemId = 11
                        },
                        new
                        {
                            Id = 72,
                            Description = "Prepare your automation idea to double your productivity. Send to your manager for approval",
                            Duration = 90,
                            Url = "",
                            UserCalendarItemId = 11
                        },
                        new
                        {
                            Id = 73,
                            Description = "Fill the NPS RemoteCamp form to summarize your experience of the week",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 11
                        },
                        new
                        {
                            Id = 74,
                            Description = "Make a weekly plan of deliveries. Recommended distribution of load is: 25/25/25/25/fix+catchup",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 12
                        },
                        new
                        {
                            Id = 75,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 12
                        },
                        new
                        {
                            Id = 76,
                            Description = "Analyse your last week performance. Plan this week improvements, document this plan. Search the tools to improve your productivity.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 12
                        },
                        new
                        {
                            Id = 77,
                            Description = "Development work",
                            Duration = 370,
                            Url = "",
                            UserCalendarItemId = 12
                        },
                        new
                        {
                            Id = 78,
                            Description = "Add 1 feedback about the RC to the WSPro deck",
                            Duration = 20,
                            Url = "",
                            UserCalendarItemId = 12
                        },
                        new
                        {
                            Id = 79,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 80,
                            Description = "CiC with Manager, discuss your innovation idea",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 81,
                            Description = "Development work",
                            Duration = 350,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 82,
                            Description = "Make TMS video of 1 unit produced",
                            Duration = 0,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 83,
                            Description = "Compare TMS for this week and the previous, document the changes",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 84,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 85,
                            Description = "Add 1 feedback about the RC to WSPro deck",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 13
                        },
                        new
                        {
                            Id = 86,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 14
                        },
                        new
                        {
                            Id = 87,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 14
                        },
                        new
                        {
                            Id = 88,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 14
                        },
                        new
                        {
                            Id = 89,
                            Description = "Finish RC feedback section in your deck",
                            Duration = 40,
                            Url = "",
                            UserCalendarItemId = 14
                        },
                        new
                        {
                            Id = 90,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 15
                        },
                        new
                        {
                            Id = 91,
                            Description = "CiC with Manager, review deck",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 15
                        },
                        new
                        {
                            Id = 92,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 15
                        },
                        new
                        {
                            Id = 93,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 15
                        },
                        new
                        {
                            Id = 94,
                            Description = "Address manager\"''\"s feedback in your deck",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 15
                        },
                        new
                        {
                            Id = 95,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 16
                        },
                        new
                        {
                            Id = 96,
                            Description = "Development work",
                            Duration = 350,
                            Url = "",
                            UserCalendarItemId = 16
                        },
                        new
                        {
                            Id = 97,
                            Description = "Check the results of your automation idea, refine it.",
                            Duration = 90,
                            Url = "",
                            UserCalendarItemId = 16
                        },
                        new
                        {
                            Id = 98,
                            Description = "Fill the NPS RemoteCamp form to summarize your experience of the week",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 16
                        },
                        new
                        {
                            Id = 99,
                            Description = "Make a weekly plan of deliveries. Recommended distribution of load is: 25/25/25/25/fix+catchup",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 17
                        },
                        new
                        {
                            Id = 100,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 17
                        },
                        new
                        {
                            Id = 101,
                            Description = "Analyse your last week performance. Plan this week improvements, document this plan. Search the tools to improve your productivity.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 17
                        },
                        new
                        {
                            Id = 102,
                            Description = "Development work",
                            Duration = 390,
                            Url = "",
                            UserCalendarItemId = 17
                        },
                        new
                        {
                            Id = 103,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 18
                        },
                        new
                        {
                            Id = 104,
                            Description = "CiC with Manager, discuss your improvements during the previous weeks and the further directions to improve, ask for the feedback",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 18
                        },
                        new
                        {
                            Id = 105,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 18
                        },
                        new
                        {
                            Id = 106,
                            Description = "Make TMS video of 1 unit produced",
                            Duration = 0,
                            Url = "",
                            UserCalendarItemId = 18
                        },
                        new
                        {
                            Id = 107,
                            Description = "Compare TMS for this week and the previous, document the changes",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 18
                        },
                        new
                        {
                            Id = 108,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 18
                        },
                        new
                        {
                            Id = 109,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 19
                        },
                        new
                        {
                            Id = 110,
                            Description = "Development work",
                            Duration = 400,
                            Url = "",
                            UserCalendarItemId = 19
                        },
                        new
                        {
                            Id = 111,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 19
                        },
                        new
                        {
                            Id = 112,
                            Description = "Fill the \"Results\" section in the deck (previous 3 weeks)",
                            Duration = 20,
                            Url = "",
                            UserCalendarItemId = 19
                        },
                        new
                        {
                            Id = 113,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 20
                        },
                        new
                        {
                            Id = 114,
                            Description = "CiC with Manager, final review deck, ask for the feedback",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 20
                        },
                        new
                        {
                            Id = 115,
                            Description = "Development work",
                            Duration = 380,
                            Url = "",
                            UserCalendarItemId = 20
                        },
                        new
                        {
                            Id = 116,
                            Description = "Technical coaching session",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 20
                        },
                        new
                        {
                            Id = 117,
                            Description = "Address manager\"''\"s feedback in your deck",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 20
                        },
                        new
                        {
                            Id = 118,
                            Description = "Check the results of your submissions. Identify the hardest problem.",
                            Duration = 30,
                            Url = "",
                            UserCalendarItemId = 21
                        },
                        new
                        {
                            Id = 119,
                            Description = "Development work",
                            Duration = 420,
                            Url = "",
                            UserCalendarItemId = 21
                        },
                        new
                        {
                            Id = 120,
                            Description = "Fill the results for the last week to your deck",
                            Duration = 10,
                            Url = "",
                            UserCalendarItemId = 21
                        },
                        new
                        {
                            Id = 121,
                            Description = "Graduation panel",
                            Duration = 20,
                            Url = "",
                            UserCalendarItemId = 21
                        });
                });

            modelBuilder.Entity("RemoteCamp.Portal.Core.Database.Model.UserCalendarItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsCompleted");

                    b.Property<int>("UserCalendarItemId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCalendarItemStatus");
                });

            modelBuilder.Entity("RemoteCamp.Portal.Core.Database.Model.UserCalendarItemAction", b =>
                {
                    b.HasOne("RemoteCamp.Portal.Core.Database.Model.UserCalendarItem", "UserCalendarItem")
                        .WithMany()
                        .HasForeignKey("UserCalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RemoteCamp.Portal.Core.Database.Model.UserCalendarItemStatus", b =>
                {
                    b.HasOne("RemoteCamp.Portal.Core.Database.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
